services:
  - type: web
    name: form-url-token-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 1000
    envVars:
      - key: SECRET
        value: super-secret-token
